spring:  
  application:  
    name: consumer
server:
  port : 8081
  
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      consumerService:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 75
        slowCallDurationThreshold: 5000ms
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 3s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
